### PR TITLE
Vinod Supnekar - Feed API Challenge

### PR DESCRIPTION
**Pull request by vinodsupnekar**

### CODE REVIEW

**Review by caiozullo — COMMENTED** [review]
Hi @vinodsupnekar, thank you for the Pull Request.

Please follow the instructions in the `README.md` file to pass the challenge.

For example, your PR is missing key items such as:

- Set the correct name in the PR
- Uncomment and make all tests pass (one at a time)
- Don't change the protocol interfaces (e.g., don't change the FeedLoader and the HTTPClient protocol). **You only need to change the RemoteFeedLoader.swift file to implement the load method.**

Review the instructions in the `README.md` and push your changes once you're done. Thank you!

**Comment by vinodsupnekar** [comment]
i have done required changes .please review and revert. Thank you.

**Comment by vinodsupnekar** [comment]
I have force pushed my code in git from local.So do i need to do something extra to push those changes to ur code.
Or just need to close this request and open another?

**Comment by caiozullo** [comment]
Hi @vinodsupnekar, you need to push your changes.

**Comment by vinodsupnekar** [comment]
I have pushed my changes with commit "feel api challange done".Let me know if u can see it.

**Comment by caiozullo** [comment]
Hi @vinodsupnekar! No, I cannot see it. Once you push your changes, they should be visible in this PR but there haven't been any changes. 

Don't forget to also rename the PR following the instructions in the `README.md` file.

**Comment by vinodsupnekar** [comment]
Hi Caio,
   Please see below attachment  for your reference.
Screenshot 2020-10-14 at 10 25 22 AM
Screenshot 2020-10-14 at 10 24 35 AM
Screenshot 2020-10-14 at 10 24 08 AM

I see my latest commit in my GitHub branch , but not able to see the updated Pull Request.

**Comment by caiozullo** [comment]
HI @vinodsupnekar,

To pass the challenge, the changes must be in the PR. Feel free to create a new PR if you're having issues with this one.

**Comment by vinodsupnekar** [comment]
ok.i will close this one and create new pull request.

**Pull request closed without merging**
